---
title       : Interactive Documents with R
subtitle    : Slidify + Shiny
author      : Pilar
job         : R Hacker
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : solarized_light     
widgets     : [bootstrap, quiz, ggplot2, reshape2, Leaflet, googleVis, RJSONIO, interactive]   
ext_widgets : {rCharts: ["libraries/nvd3", "libraries/morris", "libraries/highlights"]} 
mode        : selfcontained # {standalone, draft}
--- &radio

## Inject Interactivity

What is 1 + 1?

1. 1
2. _2_
3. 3
4. 4

*** .hint

This is a hint

*** .explanation

This is an explanation

--- 

## Interactive chart

```{r echo = F, results = 'asis'}
require(rCharts)
haireye = as.data.frame(HairEyeColor)
n1 <- nPlot(Freq ~ Hair, group = 'Eye', type = 'multiBarChart',
  data = subset(haireye, Sex == 'Male')
)
n1$print('chart1')
```

--- 

## Interactive with Morris

```{r echo=F, results = 'asis'}
data(economics, package = 'ggplot2')
econ <- transform(economics, date = as.character(date))
m1 <- mPlot(x = 'date', y = c('psavert', 'uempmed'), type = 'Line',
            data = econ)
m1$set(pointSize = 0, lineWidth = 1)
m1$save('m1.html', cdn=TRUE)
cat('<iframe src="m1.html" width=100%, height=600></iframe>')
```

---

## Interactive with xCharts

```{r echo=FALSE, results = 'asis'}
require(reshape2)
uspeexp<-melt(USPersonalExpenditure)
names(uspeexp)[1:2]=c("category", "year")

x1<-xPlot(value~year, group="category", data=uspeexp, type="line-dotted")
x1$save('x1.html', cdn=TRUE)          
cat('<iframe src="x1.html" width=100%, height=600></iframe>')
```

---

## Interactive with Leaflet

```{r echo=FALSE, results = 'asis'}
map3<-Leaflet$new()
map3$setView(c(51.505, -0.09), zoom=13)
map3$marker(c(51.5, -0.09), bindPopup="<p> Hi. I am a popup </p>")
map3$marker(c(51.495, -0.083), bindPopup="<p> Hi. I am another popup </p>")
map3$save('map3.html', cdn=TRUE)   
cat('<iframe src="map3.html" width=100%, height=600></iframe>')
```

---

## Interactive Rickshaw

```{r echo=FALSE, results = 'asis'}
require(reshape2)
usp = reshape2::melt(USPersonalExpenditure)
names(usp)[1:2]=c("Var1", "Var2")
usp$Var2<-as.numeric(as.POSIXct(paste0(usp$Var2, "-01-01")))
p4 <- Rickshaw$new()
p4$layer(value ~ Var2, group = 'Var1', data = usp, type = 'area')
p4$set(slider=TRUE)
p4$save('p4.html', cdn=TRUE)   
cat('<iframe src="p4.html" width=100%, height=600></iframe>')
```

---

## Interactive Highchart Example 1

```{r echo=FALSE, results = 'asis'}

h1<- hPlot(x="Wr.Hnd", y="NW.Hnd", data=MASS::survey, type=c("line","bubble","scatter"), group="Clap", size="Age")
h1$save('h1.html', cdn=TRUE)   
cat('<iframe src="h1.html" width=100%, height=600></iframe>')
```

---

## Interactive Highchart Example 2

```{r echo=FALSE, results = 'asis'}

h2 <- Highcharts$new()
h2$chart(type = "spline")
h2$series(data = c(1, 3, 2, 4, 5, 4, 6, 2, 3, 5, NA), dashStyle = "longdash")
h2$series(data = c(NA, 4, 1, 3, 4, 2, 9, 1, 2, 3, 4), dashStyle = "shortdot")
h2$legend(symbolWidth = 80)
h2$save('h2.html', cdn=TRUE)   
cat('<iframe src="h2.html" width=100%, height=600></iframe>')
```

--- 

```{r echo=FALSE, results = 'asis'}
require(rCharts)
df <- data.frame(label=c("US", "GB", "BR"), val1=c(1,3,4), val2=c(23,12,32))
Line <- gvisLineChart(df, xvar="label", yvar=c("val1","val2"),
        options=list(title="Hello World", legend="bottom",
                titleTextStyle="{color:'red', fontSize:18}",                         
                vAxis="{gridlines:{color:'red', count:3}}",
                hAxis="{title:'My Label', 
                titleTextStyle:{color:'blue'}}",
                series="[{color:'green', targetAxisIndex: 0}, 
                         {color: 'blue',targetAxisIndex:1}]",
                vAxes="[{title:'Value 1 (%)', format:'##,######%'}, 
                                  {title:'Value 2 (\U00A3)'}]",                          
                curveType="function", width=500, height=300                         
                ))

Line$save('Line.html', cdn=TRUE)   
cat('<iframe src="Line.html" width=100%, height=600></iframe>')

```
